sdm845-common: fingerprint: Remove IXiaomiFingerprint service dep
This is no longer needed.

Change-Id: I2e283a0599a4c6b3b4b1ba7673c2e9efd00e6b12
Signed-off-by: XtremeOrnob <xtreme.ornob@gmail.com>

Fix For:-
FAILED: //device/xiaomi/sdm845-common/fingerprint:android.hardware.biometrics.fingerprint@2.3-service.xiaomi_sdm845 clang++ BiometricsFingerprint.cpp
Outputs: out/soong/.intermediates/device/xiaomi/sdm845-common/fingerprint/android.hardware.biometrics.fingerprint@2.3-service.xiaomi_sdm845/android_vendor.32_arm64_armv8-2a_kryo385/obj/device/xiaomi/sdm845-common/fingerprint/BiometricsFi>
Error: exited with code: 1
Command: PWD=/proc/self/cwd /bin/ccache prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang++ -c -D__ANDROID_VNDK__ -D__ANDROID_VENDOR__  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit>
Output:
^[[1mdevice/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:394:41: ^[[0m^[[0;1;31merror: ^[[0m^[[1mno member named 'GetProperty' in namespace 'android::base'^[[0m
    std::string device = android::base::GetProperty("ro.product.device", "");
^[[0;1;32m                         ~~~~~~~~~~~~~~~^
^[[0m^[[1mdevice/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:400:9: ^[[0m^[[0;1;31merror: ^[[0m^[[1muse of undeclared identifier 'DISPPARAM_PATH'^[[0m
    set(DISPPARAM_PATH, DISPPARAM_HBM_FOD_ON);
^[[0;1;32m        ^
^[[0m^[[1mdevice/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:400:25: ^[[0m^[[0;1;31merror: ^[[0m^[[1muse of undeclared identifier 'DISPPARAM_HBM_FOD_ON'^[[0m
    set(DISPPARAM_PATH, DISPPARAM_HBM_FOD_ON);
^[[0;1;32m                        ^
^[[0m^[[1mdevice/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:401:30: ^[[0m^[[0;1;31merror: ^[[0m^[[1muse of undeclared identifier 'COMMAND_NIT'^[[0m
    mDevice->extCmd(mDevice, COMMAND_NIT, PARAM_NIT_630_FOD);
^[[0;1;32m                             ^
^[[0m^[[1mdevice/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:401:43: ^[[0m^[[0;1;31merror: ^[[0m^[[1muse of undeclared identifier 'PARAM_NIT_630_FOD'^[[0m
    mDevice->extCmd(mDevice, COMMAND_NIT, PARAM_NIT_630_FOD);
^[[0;1;32m                                          ^
^[[0m^[[1mdevice/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:402:9: ^[[0m^[[0;1;31merror: ^[[0m^[[1muse of undeclared identifier 'FOD_STATUS_PATH'^[[0m
    set(FOD_STATUS_PATH, FOD_STATUS_ON);
^[[0;1;32m        ^
^[[0m^[[1mdevice/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:402:26: ^[[0m^[[0;1;31merror: ^[[0m^[[1muse of undeclared identifier 'FOD_STATUS_ON'^[[0m
    set(FOD_STATUS_PATH, FOD_STATUS_ON);
^[[0;1;32m                         ^
^[[0m^[[1mdevice/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:407:9: ^[[0m^[[0;1;31merror: ^[[0m^[[1muse of undeclared identifier 'DISPPARAM_PATH'^[[0m
    set(DISPPARAM_PATH, DISPPARAM_HBM_FOD_OFF);
^[[0;1;32m        ^
^[[0m^[[1mdevice/xiaomi/sdm845-common/fingerprint/BiometricsFingerprint.cpp:407:25: ^[[0m^[[0;1;31merror: ^[[0m^[[1muse of undeclared identifier 'DISPPARAM_HBM_FOD_OFF'^[[0m